### ISSUE TITLE
Minimal interface, with regard to the type of the keys

### ISSUE THREAD

**Issue by danse** [eskimor/purescript-localstorage#1]
Hi, i am pasting this from Reddit, because i had some messages disappearing there, so i prefer to continue the discussion here on Github.

To summarise, i began asking you what is the utility of the fancy types for the keys, and you answered:

> You got this right. You can use the Raw interface if you like, but I don't really get why anyone would want this.
> 
> The type safe interface basically only requires you to list the keys you are going to use. (Ok currently additional smart constructors are needed) Which is really very little work (this was actually a very important design criteria) and saves you from misspelling keys or using the wrong key!
> 
> Also, because the keys encode the type you are going to retrieve, you will never need any type annotations. If keys were plain strings and you would retrieve a value, let's say from the repl, a type annotation would be necessary. - So especially if you just want to try it out an explicit key type makes sense.
> 
> Ok, having said that: I am not opposed to including an additional interface where keys are strings, and values are encoded/decoded for you. If people want/need that, I am happy to accept my first pull request :-)
> 
> in fact - even the example in the Readme, would need an explicit type annotation, when written with strings as keys:
> 
>    user <- localStorage.getItem "UserConfig"
>    log $ gShow user
> 
> This would not work without a type annotation, as gShow is also generic - so the compiler has no way of figuring out of what type the retrieved value is.

Alright, this is interesting. Thus the type fanciness of the keys allows the compiler to infer the type of the value. Well, this is a valid reason, thanks for elaborating. The value added was not clear to me at first. I will close this issue, but it will stay as a form of documentation for the future. Cheers!

**Comment by eskimor** [comment]
Thanks! I already wondered whether you even got my answers on Reddit, glad you did and it is working out for you!

Wuhu -my first issue and it is closed already :-)

**Comment by eskimor** [comment]
Updated the readme accordingly.

**Comment by danse** [comment]
:+1:

**Comment by esad** [comment]
@eskimor Could the interface be simplified though?

Why go over the trouble of requiring the key to be generic just to call `gShow` to get the string representation when we could let the user supply the string value for the key:

```
data Key a = Key String -- Exported by the library

myKey :: Key Foo
myKey = Key "foo"
```

The string value can then be extracted with `\(Key str) -> str` instead of `gShow`.

**Comment by eskimor** [comment]
That is actually a quite elegant solution. The manual string specification makes it a little less type safe: If you accidentally (copy&paste) use the same string twice, you would get a runtime error, instead of a compiler error. Other than that I like it, but I also don't really see a problem with the status quo, so I am a bit hesitant to do this breaking change.

**Comment by esad** [comment]
Another advantage of the above approach is that one can actually specify the key to be used. This can be useful if you have some legacy data in the localstorage that you don't want to throw away.

**Comment by eskimor** [comment]
Or you just want more readable keys, which is nice for debugging. I think I am sold and would accept a PR ;-)
