### ISSUE TITLE
Mock storage

### ISSUE THREAD

**Issue by texastoland** [eskimor/purescript-localstorage#2]
Would it make sense to provide a mock `Storage` that just saves to a `Foreign` for testing?

**Comment by eskimor** [comment]
Sure - I don't see why not. I'd definitely accept a PR :-)

**Comment by texastoland** [comment]
Do you want tests? Prefer a framework or none?

**Comment by eskimor** [comment]
Tests would be awesome of course! I previously use purescript-assert for testing, but you can use what-ever framework you see fit. Thank you!
