### ISSUE TITLE
DOM effect

### ISSUE THREAD

**Issue by texastoland** [eskimor/purescript-localstorage#3]
Should `localStorage` and `sessionStorage` have the type `Eff (storage :: STORAGE, dom :: DOM | e) Storage` since they're dependent on `Window`?

**Comment by eskimor** [comment]
I think the more precise STORAGE effect is better. But I don't really mind, if there is some convention to follow which would suggest to use DOM - I would definitely go for it.

**Comment by texastoland** [comment]
I meant in addition. The idea is even if it has a `storage` effect it's not reproducible in different `Window`s e.g. an iFrame. I'll try to add it in a separate PR.

**Comment by eskimor** [comment]
Ok - I see what you mean. You want the DOM effect to make it more obvious that the result of the operations depend on the current domain in use? And that they are dependent on a browser environment?

Makes sense! :-)

**Comment by eskimor** [comment]
Although there is one drawback: It makes it less easy to switch between storage backends if they have different effect types.

**Comment by texastoland** [comment]
The only thing that should change is:

```purs
type EffLocalStorage eff = Eff (storage :: STORAGE, dom :: DOM | eff)
type EffMockStorage eff = Eff (storage :: STORAGE | eff)
```

**Comment by texastoland** [comment]
I implemented it this weekend but haven't pushed since my IDE started acting funky late last night. Basically your storage types don't change at all. It's accessing `localStorage` and `sessionStorage` itself which now has the type `forall e. Eff (dom :: DOM | e) Storage`. Likewise I should've realized my mock storage is really `newMockStorage :: forall e. Eff (ref :: REF | e) Storage` (`Unit -> a` is almost always wrong). I think the rows make it vaguely clear the former depends on the browser environment and the latter introduces a new globally mutable reference.

One question: @garyb I'm only depending on `dom` and `refs` for their effect rows. Am I doing it right?

**Comment by garyb** [comment]
@texastoland yes, definitely - that's one of the reasons `dom` is low level, so that it can be used just for the effect or a handful of functions without pulling in a bunch of additional dependencies you might not want in a project.

Duplicated effect types/labels are a nightmare, as they make the types mutually incompatible without unsafe coercion.

**Comment by texastoland** [comment]
There needs to be a 🙏 reaction 👌

**Comment by eskimor** [comment]
I believe this can be closed right? The get functions just get the DOM effect, the remains still use STORAGE - this makes a lot of sense.
